name: Dispatch Proxy

on:
  repository_dispatch:
    types: [proxy]

jobs:
  forward:
    runs-on: ubuntu-latest

    steps:
      - name: Forward request to update-stats
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/nagygabriel/gabriel-counter/dispatches \
            -d '{"event_type":"update-stats","client_payload":'"${{ toJson(github.event.client_payload) }}"'}'
