name: Dispatch Proxy

on:
  repository_dispatch:
    types: [proxy]

jobs:
  forward:
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue with token
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/nagygabriel/gabriel-counter/issues \
            -d "{\"title\":\"Stat update\",\"body\":\"${{ toJson(github.event.client_payload) }}\"}"
